set(_CATKIN_CURRENT_PACKAGE "ce30_driver_ros")
set(ce30_driver_ros_VERSION "0.0.0")
set(ce30_driver_ros_MAINTAINER "kevin <kevin@todo.todo>")
set(ce30_driver_ros_PACKAGE_FORMAT "2")
set(ce30_driver_ros_BUILD_DEPENDS "ce30_driver" "roscpp" "sensor_msgs")
set(ce30_driver_ros_BUILD_EXPORT_DEPENDS "ce30_driver" "roscpp" "sensor_msgs")
set(ce30_driver_ros_BUILDTOOL_DEPENDS "catkin")
set(ce30_driver_ros_BUILDTOOL_EXPORT_DEPENDS )
set(ce30_driver_ros_EXEC_DEPENDS "ce30_driver" "roscpp" "sensor_msgs")
set(ce30_driver_ros_RUN_DEPENDS "ce30_driver" "roscpp" "sensor_msgs")
set(ce30_driver_ros_TEST_DEPENDS )
set(ce30_driver_ros_DOC_DEPENDS )
set(ce30_driver_ros_URL_WEBSITE "")
set(ce30_driver_ros_URL_BUGTRACKER "")
set(ce30_driver_ros_URL_REPOSITORY "")
set(ce30_driver_ros_DEPRECATED "")